apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-dns-updater
data:
{{- range $i, $record := .Values.cloudflare.records }}
  config_{{ $i }}.json: |
    {
    "zone": "{{ $.Values.cloudflare.zone }}",
    "record": "{{ $record.id }}",
    "domain": "{{ $record.name }}"
    }
{{- end }}
